# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0915deafe0140e534ea5dfaab7a9c7ab5e2b5bb2163233536e093e024f6b17e4473833366815da152024e4c9163338580972f467e0280dc3e4ccff6f41a0ce40

test:
  secret_key_base: 759cc75eb8963751899ae497adf3249618e85b510c38065e9a0b955e50779ce3e34a939edc7d90ff29f8e9ace4e4a9fe4d3e21cedea7ebb5d762eacda0bd36f4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
